import type { NavItem, Tool } from '@/types'
import navConfig from '../../config/navigation.json'

export const navItems: NavItem[] = navConfig as NavItem[]

export const tools: Tool[] = [
  // ── Editors ──
  { id: 'markdown-editor', name: 'Markdown Editor', description: 'A full-featured Markdown editor with real-time preview and syntax highlighting.', category: 'editor', slug: '/markdown-editor/', icon: 'edit' },
  { id: 'live-markdown-editor', name: 'Live Markdown Editor', description: 'Edit Markdown and see the rendered output update instantly as you type.', category: 'editor', slug: '/live-markdown-editor/', icon: 'edit' },
  { id: 'split-view-editor', name: 'Split View Editor', description: 'View your Markdown source and rendered preview side by side.', category: 'editor', slug: '/split-view-editor/', icon: 'edit' },
  { id: 'wysiwyg-markdown-editor', name: 'WYSIWYG Markdown Editor', description: 'Edit Markdown visually with a what-you-see-is-what-you-get interface.', category: 'editor', slug: '/wysiwyg-markdown-editor/', icon: 'edit' },
  { id: 'markdown-playground', name: 'Markdown Playground', description: 'Experiment with Markdown syntax and see instant rendered results.', category: 'editor', slug: '/markdown-playground/', icon: 'play' },
  { id: 'github-markdown-preview', name: 'GitHub Markdown Preview', description: 'Preview Markdown exactly as it will appear on GitHub.', category: 'editor', slug: '/github-markdown-preview/', icon: 'eye' },
  { id: 'commonmark-editor', name: 'CommonMark Editor', description: 'Write Markdown that strictly follows the CommonMark specification.', category: 'editor', slug: '/commonmark-editor/', icon: 'edit' },
  { id: 'gfm-editor', name: 'GFM Editor', description: 'Edit Markdown with GitHub Flavored Markdown extensions and features.', category: 'editor', slug: '/gfm-editor/', icon: 'edit' },
  { id: 'obsidian-markdown-editor', name: 'Obsidian Markdown Editor', description: 'A Markdown editor styled after Obsidian with wiki links and embeds.', category: 'editor', slug: '/obsidian-markdown-editor/', icon: 'edit' },
  { id: 'notion-markdown-editor', name: 'Notion Markdown Editor', description: 'Write Markdown with a Notion-inspired block-based editing experience.', category: 'editor', slug: '/notion-markdown-editor/', icon: 'edit' },
  { id: 'markdown-notes-editor', name: 'Markdown Notes Editor', description: 'Take notes in Markdown with organization and quick-search features.', category: 'editor', slug: '/markdown-notes-editor/', icon: 'file' },
  { id: 'multi-file-markdown-editor', name: 'Multi-file Markdown Editor', description: 'Edit and manage multiple Markdown files simultaneously.', category: 'editor', slug: '/multi-file-markdown-editor/', icon: 'file' },
  { id: 'fullscreen-markdown-editor', name: 'Fullscreen Markdown Editor', description: 'Write Markdown distraction-free in fullscreen mode.', category: 'editor', slug: '/fullscreen-markdown-editor/', icon: 'edit' },
  { id: 'side-by-side-preview', name: 'Side-by-Side Preview', description: 'View source and rendered Markdown next to each other in real time.', category: 'editor', slug: '/side-by-side-preview/', icon: 'eye' },
  { id: 'live-html-preview', name: 'Live HTML Preview', description: 'See the HTML output of your Markdown update live as you type.', category: 'editor', slug: '/live-html-preview/', icon: 'code' },
  { id: 'dark-mode-markdown-editor', name: 'Dark Mode Markdown Editor', description: 'Write Markdown in a comfortable dark-themed editing environment.', category: 'editor', slug: '/dark-mode-markdown-editor/', icon: 'edit' },
  { id: 'ai-markdown-editor', name: 'AI Markdown Editor', description: 'Write Markdown with AI-powered autocomplete and content suggestions.', category: 'editor', slug: '/ai-markdown-editor/', icon: 'wand' },
  { id: 'collaborative-markdown-editor', name: 'Collaborative Markdown Editor', description: 'Edit Markdown documents collaboratively with others in real time.', category: 'editor', slug: '/collaborative-markdown-editor/', icon: 'edit' },
  { id: 'markdown-scratchpad', name: 'Markdown Scratchpad', description: 'A quick scratchpad for jotting down Markdown notes on the fly.', category: 'editor', slug: '/markdown-scratchpad/', icon: 'file' },
  { id: 'markdown-notebook', name: 'Markdown Notebook', description: 'An interactive notebook combining Markdown with executable code cells.', category: 'editor', slug: '/markdown-notebook/', icon: 'file' },
  { id: 'mobile-markdown-editor', name: 'Mobile Markdown Editor', description: 'A touch-friendly Markdown editor optimized for mobile devices.', category: 'editor', slug: '/mobile-markdown-editor/', icon: 'edit' },
  { id: 'rich-text-to-markdown-editor', name: 'Rich Text to Markdown Editor', description: 'Paste rich text and have it automatically converted to Markdown.', category: 'editor', slug: '/rich-text-to-markdown-editor/', icon: 'edit' },
  { id: 'markdown-code-editor', name: 'Markdown Code Editor', description: 'Write Markdown with code editor features like line numbers and syntax highlighting.', category: 'editor', slug: '/markdown-code-editor/', icon: 'code' },
  { id: 'documentation-editor', name: 'Documentation Editor', description: 'A specialized Markdown editor for writing technical documentation.', category: 'editor', slug: '/documentation-editor/', icon: 'file' },
  { id: 'blog-post-editor', name: 'Blog Post Editor', description: 'Write and format blog posts using Markdown with a focused editor.', category: 'editor', slug: '/blog-post-editor/', icon: 'edit' },
  { id: 'readme-editor', name: 'README Editor', description: 'Edit README files with previews and project-specific formatting.', category: 'editor', slug: '/readme-editor/', icon: 'edit' },
  { id: 'wiki-editor', name: 'Wiki Editor', description: 'A Markdown editor designed for creating and editing wiki pages.', category: 'editor', slug: '/wiki-editor/', icon: 'file' },
  { id: 'knowledge-base-editor', name: 'Knowledge Base Editor', description: 'Write knowledge base articles in Markdown with structured organization.', category: 'editor', slug: '/knowledge-base-editor/', icon: 'file' },
  { id: 'markdown-canvas', name: 'Markdown Canvas', description: 'A freeform canvas for arranging and connecting Markdown notes visually.', category: 'editor', slug: '/markdown-canvas/', icon: 'layout' },
  { id: 'markdown-studio', name: 'Markdown Studio', description: 'A full-featured Markdown authoring studio with advanced editing tools.', category: 'editor', slug: '/markdown-studio/', icon: 'layout' },

  // ── Converters ──
  { id: 'markdown-to-html', name: 'Markdown to HTML', description: 'Convert Markdown text to clean, semantic HTML markup instantly.', category: 'converter', slug: '/markdown-to-html/', icon: 'code' },
  { id: 'html-to-markdown', name: 'HTML to Markdown', description: 'Convert HTML back into readable Markdown format.', category: 'converter', slug: '/html-to-markdown/', icon: 'code' },
  { id: 'markdown-to-pdf', name: 'Markdown to PDF', description: 'Convert Markdown documents to professional PDF files.', category: 'converter', slug: '/markdown-to-pdf/', icon: 'file' },
  { id: 'pdf-to-markdown', name: 'PDF to Markdown', description: 'Extract and convert PDF content into Markdown format.', category: 'converter', slug: '/pdf-to-markdown/', icon: 'file' },
  { id: 'markdown-to-docx', name: 'Markdown to DOCX', description: 'Convert Markdown files to Microsoft Word DOCX format.', category: 'converter', slug: '/markdown-to-docx/', icon: 'file' },
  { id: 'docx-to-markdown', name: 'DOCX to Markdown', description: 'Convert Word documents into clean Markdown format.', category: 'converter', slug: '/docx-to-markdown/', icon: 'file' },
  { id: 'markdown-to-odt', name: 'Markdown to ODT', description: 'Convert Markdown to OpenDocument Text format.', category: 'converter', slug: '/markdown-to-odt/', icon: 'file' },
  { id: 'odt-to-markdown', name: 'ODT to Markdown', description: 'Convert OpenDocument Text files to Markdown.', category: 'converter', slug: '/odt-to-markdown/', icon: 'file' },
  { id: 'markdown-to-rtf', name: 'Markdown to RTF', description: 'Convert Markdown to Rich Text Format.', category: 'converter', slug: '/markdown-to-rtf/', icon: 'file' },
  { id: 'rtf-to-markdown', name: 'RTF to Markdown', description: 'Convert Rich Text Format documents to Markdown.', category: 'converter', slug: '/rtf-to-markdown/', icon: 'file' },
  { id: 'markdown-to-txt', name: 'Markdown to TXT', description: 'Strip Markdown formatting and convert to plain text.', category: 'converter', slug: '/markdown-to-txt/', icon: 'file' },
  { id: 'txt-to-markdown', name: 'TXT to Markdown', description: 'Convert plain text files into Markdown format.', category: 'converter', slug: '/txt-to-markdown/', icon: 'file' },
  { id: 'markdown-to-epub', name: 'Markdown to EPUB', description: 'Convert Markdown documents to EPUB ebook format.', category: 'converter', slug: '/markdown-to-epub/', icon: 'file' },
  { id: 'epub-to-markdown', name: 'EPUB to Markdown', description: 'Convert EPUB ebooks into Markdown format.', category: 'converter', slug: '/epub-to-markdown/', icon: 'file' },
  { id: 'markdown-to-latex', name: 'Markdown to LaTeX', description: 'Convert Markdown to LaTeX document format for academic publishing.', category: 'converter', slug: '/markdown-to-latex/', icon: 'code' },
  { id: 'latex-to-markdown', name: 'LaTeX to Markdown', description: 'Convert LaTeX documents into readable Markdown.', category: 'converter', slug: '/latex-to-markdown/', icon: 'code' },
  { id: 'markdown-to-bbcode', name: 'Markdown to BBCode', description: 'Convert Markdown to BBCode for forum posting.', category: 'converter', slug: '/markdown-to-bbcode/', icon: 'code' },
  { id: 'bbcode-to-markdown', name: 'BBCode to Markdown', description: 'Convert BBCode forum markup into Markdown.', category: 'converter', slug: '/bbcode-to-markdown/', icon: 'code' },
  { id: 'markdown-to-json', name: 'Markdown to JSON', description: 'Convert Markdown documents into structured JSON format.', category: 'converter', slug: '/markdown-to-json/', icon: 'code' },
  { id: 'json-to-markdown', name: 'JSON to Markdown', description: 'Convert JSON data into formatted Markdown output.', category: 'converter', slug: '/json-to-markdown/', icon: 'code' },
  { id: 'markdown-to-yaml', name: 'Markdown to YAML', description: 'Convert Markdown front matter and content to YAML.', category: 'converter', slug: '/markdown-to-yaml/', icon: 'code' },
  { id: 'yaml-to-markdown', name: 'YAML to Markdown', description: 'Convert YAML data into Markdown formatted documents.', category: 'converter', slug: '/yaml-to-markdown/', icon: 'code' },
  { id: 'markdown-to-xml', name: 'Markdown to XML', description: 'Convert Markdown content into XML markup.', category: 'converter', slug: '/markdown-to-xml/', icon: 'code' },
  { id: 'xml-to-markdown', name: 'XML to Markdown', description: 'Convert XML data into readable Markdown format.', category: 'converter', slug: '/xml-to-markdown/', icon: 'code' },
  { id: 'markdown-to-csv', name: 'Markdown to CSV', description: 'Convert Markdown tables to CSV spreadsheet data.', category: 'converter', slug: '/markdown-to-csv/', icon: 'table' },
  { id: 'csv-to-markdown', name: 'CSV to Markdown', description: 'Convert CSV data into Markdown table format.', category: 'converter', slug: '/csv-to-markdown/', icon: 'table' },
  { id: 'markdown-to-tsv', name: 'Markdown to TSV', description: 'Convert Markdown tables to tab-separated values.', category: 'converter', slug: '/markdown-to-tsv/', icon: 'table' },
  { id: 'tsv-to-markdown', name: 'TSV to Markdown', description: 'Convert tab-separated values into Markdown tables.', category: 'converter', slug: '/tsv-to-markdown/', icon: 'table' },
  { id: 'markdown-to-excel', name: 'Markdown to Excel', description: 'Convert Markdown tables to Excel spreadsheet format.', category: 'converter', slug: '/markdown-to-excel/', icon: 'table' },
  { id: 'excel-to-markdown', name: 'Excel to Markdown', description: 'Convert Excel spreadsheets to Markdown tables.', category: 'converter', slug: '/excel-to-markdown/', icon: 'table' },
  { id: 'markdown-to-powerpoint', name: 'Markdown to PowerPoint', description: 'Convert Markdown outlines into PowerPoint presentations.', category: 'converter', slug: '/markdown-to-powerpoint/', icon: 'file' },
  { id: 'powerpoint-to-markdown', name: 'PowerPoint to Markdown', description: 'Extract text from PowerPoint slides into Markdown.', category: 'converter', slug: '/powerpoint-to-markdown/', icon: 'file' },
  { id: 'markdown-to-jupyter-notebook', name: 'Markdown to Jupyter Notebook', description: 'Convert Markdown to Jupyter notebook format.', category: 'converter', slug: '/markdown-to-jupyter-notebook/', icon: 'code' },
  { id: 'jupyter-notebook-to-markdown', name: 'Jupyter Notebook to Markdown', description: 'Extract Markdown cells from Jupyter notebooks.', category: 'converter', slug: '/jupyter-notebook-to-markdown/', icon: 'code' },
  { id: 'markdown-to-react-jsx', name: 'Markdown to React JSX', description: 'Convert Markdown content into React JSX components.', category: 'converter', slug: '/markdown-to-react-jsx/', icon: 'code' },
  { id: 'jsx-to-markdown', name: 'JSX to Markdown', description: 'Convert React JSX components back to Markdown.', category: 'converter', slug: '/jsx-to-markdown/', icon: 'code' },
  { id: 'markdown-to-vue', name: 'Markdown to Vue', description: 'Convert Markdown to Vue.js template format.', category: 'converter', slug: '/markdown-to-vue/', icon: 'code' },
  { id: 'vue-to-markdown', name: 'Vue to Markdown', description: 'Convert Vue.js templates into Markdown.', category: 'converter', slug: '/vue-to-markdown/', icon: 'code' },
  { id: 'markdown-to-svelte', name: 'Markdown to Svelte', description: 'Convert Markdown content into Svelte components.', category: 'converter', slug: '/markdown-to-svelte/', icon: 'code' },
  { id: 'markdown-to-astro', name: 'Markdown to Astro', description: 'Convert Markdown to Astro component format.', category: 'converter', slug: '/markdown-to-astro/', icon: 'code' },
  { id: 'markdown-to-docusaurus', name: 'Markdown to Docusaurus', description: 'Convert Markdown to Docusaurus documentation format.', category: 'converter', slug: '/markdown-to-docusaurus/', icon: 'code' },
  { id: 'markdown-to-mkdocs', name: 'Markdown to MkDocs', description: 'Convert Markdown to MkDocs documentation format.', category: 'converter', slug: '/markdown-to-mkdocs/', icon: 'code' },
  { id: 'markdown-to-hugo', name: 'Markdown to Hugo', description: 'Convert Markdown to Hugo static site format.', category: 'converter', slug: '/markdown-to-hugo/', icon: 'code' },
  { id: 'markdown-to-jekyll', name: 'Markdown to Jekyll', description: 'Convert Markdown to Jekyll static site format.', category: 'converter', slug: '/markdown-to-jekyll/', icon: 'code' },
  { id: 'markdown-to-nextjs', name: 'Markdown to Next.js', description: 'Convert Markdown to Next.js MDX-ready format.', category: 'converter', slug: '/markdown-to-nextjs/', icon: 'code' },
  { id: 'markdown-to-mdx', name: 'Markdown to MDX', description: 'Convert Markdown to MDX with JSX support.', category: 'converter', slug: '/markdown-to-mdx/', icon: 'code' },
  { id: 'mdx-to-markdown', name: 'MDX to Markdown', description: 'Convert MDX files back to plain Markdown.', category: 'converter', slug: '/mdx-to-markdown/', icon: 'code' },
  { id: 'markdown-to-asciidoc', name: 'Markdown to AsciiDoc', description: 'Convert Markdown to AsciiDoc format.', category: 'converter', slug: '/markdown-to-asciidoc/', icon: 'code' },
  { id: 'asciidoc-to-markdown', name: 'AsciiDoc to Markdown', description: 'Convert AsciiDoc documents to Markdown.', category: 'converter', slug: '/asciidoc-to-markdown/', icon: 'code' },
  { id: 'universal-markdown-converter', name: 'Universal Markdown Converter', description: 'Convert between any two document formats with Markdown as the bridge.', category: 'converter', slug: '/universal-markdown-converter/', icon: 'wand' },
  { id: 'markdown-to-mermaid', name: 'Markdown ↔ Mermaid', description: 'Convert between Markdown and Mermaid diagram syntax.', category: 'converter', slug: '/markdown-to-mermaid/', icon: 'code' },
  { id: 'markdown-to-restructuredtext', name: 'Markdown ↔ reStructuredText', description: 'Convert between Markdown and reStructuredText formats.', category: 'converter', slug: '/markdown-to-restructuredtext/', icon: 'code' },
  { id: 'markdown-to-textile', name: 'Markdown ↔ Textile', description: 'Convert between Markdown and Textile markup formats.', category: 'converter', slug: '/markdown-to-textile/', icon: 'code' },
  { id: 'markdown-to-org-mode', name: 'Markdown ↔ Org Mode', description: 'Convert between Markdown and Emacs Org Mode formats.', category: 'converter', slug: '/markdown-to-org-mode/', icon: 'code' },
  { id: 'markdown-to-mediawiki', name: 'Markdown ↔ MediaWiki', description: 'Convert between Markdown and MediaWiki markup.', category: 'converter', slug: '/markdown-to-mediawiki/', icon: 'code' },
  { id: 'markdown-to-confluence-wiki', name: 'Markdown ↔ Confluence Wiki', description: 'Convert between Markdown and Confluence Wiki markup.', category: 'converter', slug: '/markdown-to-confluence-wiki/', icon: 'code' },
  { id: 'markdown-to-slack-format', name: 'Markdown ↔ Slack Format', description: 'Convert between Markdown and Slack message format.', category: 'converter', slug: '/markdown-to-slack-format/', icon: 'code' },
  { id: 'markdown-to-discord-format', name: 'Markdown ↔ Discord Format', description: 'Convert between Markdown and Discord message format.', category: 'converter', slug: '/markdown-to-discord-format/', icon: 'code' },
  { id: 'markdown-to-whatsapp-format', name: 'Markdown ↔ WhatsApp Format', description: 'Convert between Markdown and WhatsApp text format.', category: 'converter', slug: '/markdown-to-whatsapp-format/', icon: 'code' },
  { id: 'batch-markdown-converter', name: 'Batch Markdown Converter', description: 'Convert multiple Markdown files between formats in one operation.', category: 'converter', slug: '/batch-markdown-converter/', icon: 'wand' },

  // ── Tables ──
  { id: 'markdown-table-generator', name: 'Markdown Table Generator', description: 'Generate Markdown tables with a visual grid interface.', category: 'table', slug: '/markdown-table-generator/', icon: 'table' },
  { id: 'markdown-table-formatter', name: 'Markdown Table Formatter', description: 'Format and align Markdown tables for clean readability.', category: 'table', slug: '/markdown-table-formatter/', icon: 'table' },
  { id: 'markdown-table-beautifier', name: 'Markdown Table Beautifier', description: 'Beautify Markdown tables with proper alignment and padding.', category: 'table', slug: '/markdown-table-beautifier/', icon: 'table' },
  { id: 'csv-to-markdown-table', name: 'CSV to Markdown Table', description: 'Convert CSV data into a formatted Markdown table.', category: 'table', slug: '/csv-to-markdown-table/', icon: 'table' },
  { id: 'excel-to-markdown-table', name: 'Excel to Markdown Table', description: 'Convert Excel spreadsheet data into Markdown tables.', category: 'table', slug: '/excel-to-markdown-table/', icon: 'table' },
  { id: 'json-to-markdown-table', name: 'JSON to Markdown Table', description: 'Convert JSON arrays of objects into Markdown tables.', category: 'table', slug: '/json-to-markdown-table/', icon: 'table' },
  { id: 'html-table-to-markdown', name: 'HTML Table to Markdown', description: 'Convert HTML table markup into Markdown table format.', category: 'table', slug: '/html-table-to-markdown/', icon: 'code' },
  { id: 'markdown-table-to-html', name: 'Markdown Table to HTML', description: 'Convert Markdown tables into HTML table elements.', category: 'table', slug: '/markdown-table-to-html/', icon: 'code' },
  { id: 'table-alignment-generator', name: 'Table Alignment Generator', description: 'Set and preview column alignment for Markdown tables.', category: 'table', slug: '/table-alignment-generator/', icon: 'table' },
  { id: 'markdown-table-sorter', name: 'Markdown Table Sorter', description: 'Sort Markdown table rows by any column.', category: 'table', slug: '/markdown-table-sorter/', icon: 'table' },
  { id: 'table-merger', name: 'Table Merger', description: 'Merge two or more Markdown tables together.', category: 'table', slug: '/table-merger/', icon: 'table' },
  { id: 'table-splitter', name: 'Table Splitter', description: 'Split a large Markdown table into smaller tables.', category: 'table', slug: '/table-splitter/', icon: 'table' },
  { id: 'responsive-table-generator', name: 'Responsive Table Generator', description: 'Create Markdown tables that work well on mobile devices.', category: 'table', slug: '/responsive-table-generator/', icon: 'table' },
  { id: 'table-validator', name: 'Table Validator', description: 'Validate Markdown table syntax and structure.', category: 'table', slug: '/table-validator/', icon: 'search' },
  { id: 'table-diff-tool', name: 'Table Diff Tool', description: 'Compare two Markdown tables and highlight differences.', category: 'table', slug: '/table-diff-tool/', icon: 'table' },
  { id: 'table-editor', name: 'Table Editor', description: 'Interactive Markdown table editor with spreadsheet-like controls.', category: 'table', slug: '/table-editor/', icon: 'table' },
  { id: 'table-column-generator', name: 'Table Column Generator', description: 'Generate columns of repeated data for Markdown tables.', category: 'table', slug: '/table-column-generator/', icon: 'table' },
  { id: 'table-row-generator', name: 'Table Row Generator', description: 'Generate rows of data for Markdown tables quickly.', category: 'table', slug: '/table-row-generator/', icon: 'table' },
  { id: 'markdown-pricing-table-generator', name: 'Markdown Pricing Table Generator', description: 'Create professional pricing tables in Markdown.', category: 'table', slug: '/markdown-pricing-table-generator/', icon: 'table' },
  { id: 'markdown-comparison-table', name: 'Markdown Comparison Table', description: 'Build feature comparison tables in Markdown format.', category: 'table', slug: '/markdown-comparison-table/', icon: 'table' },
  { id: 'github-table-generator', name: 'GitHub Table Generator', description: 'Create tables formatted for GitHub Flavored Markdown.', category: 'table', slug: '/github-table-generator/', icon: 'table' },
  { id: 'obsidian-table-generator', name: 'Obsidian Table Generator', description: 'Create tables compatible with Obsidian notes.', category: 'table', slug: '/obsidian-table-generator/', icon: 'table' },
  { id: 'notion-table-generator', name: 'Notion Table Generator', description: 'Create tables formatted for Notion pages.', category: 'table', slug: '/notion-table-generator/', icon: 'table' },
  { id: 'markdown-table-preview', name: 'Markdown Table Preview', description: 'Preview how your Markdown tables will look when rendered.', category: 'table', slug: '/markdown-table-preview/', icon: 'eye' },
  { id: 'table-playground', name: 'Table Playground', description: 'Experiment with Markdown table syntax in an interactive playground.', category: 'table', slug: '/table-playground/', icon: 'play' },

  // ── Formatters & Validators ──
  { id: 'markdown-formatter', name: 'Markdown Formatter', description: 'Format Markdown documents consistently with customizable rules.', category: 'formatter', slug: '/markdown-formatter/', icon: 'code' },
  { id: 'markdown-beautifier', name: 'Markdown Beautifier', description: 'Beautify Markdown with proper indentation and spacing.', category: 'formatter', slug: '/markdown-beautifier/', icon: 'code' },
  { id: 'markdown-linter', name: 'Markdown Linter', description: 'Lint Markdown files for style and syntax issues.', category: 'formatter', slug: '/markdown-linter/', icon: 'search' },
  { id: 'markdown-validator', name: 'Markdown Validator', description: 'Validate Markdown syntax and report errors.', category: 'formatter', slug: '/markdown-validator/', icon: 'search' },
  { id: 'markdown-cleaner', name: 'Markdown Cleaner', description: 'Clean up messy Markdown and remove unnecessary formatting.', category: 'formatter', slug: '/markdown-cleaner/', icon: 'code' },
  { id: 'markdown-minifier', name: 'Markdown Minifier', description: 'Minify Markdown by removing whitespace and comments.', category: 'formatter', slug: '/markdown-minifier/', icon: 'code' },
  { id: 'markdown-optimizer', name: 'Markdown Optimizer', description: 'Optimize Markdown for better readability and smaller file size.', category: 'formatter', slug: '/markdown-optimizer/', icon: 'code' },
  { id: 'heading-validator', name: 'Heading Validator', description: 'Validate heading structure and hierarchy in Markdown documents.', category: 'formatter', slug: '/heading-validator/', icon: 'search' },
  { id: 'broken-link-checker', name: 'Broken Link Checker', description: 'Find and report broken links in Markdown documents.', category: 'formatter', slug: '/broken-link-checker/', icon: 'search' },
  { id: 'image-link-checker', name: 'Image Link Checker', description: 'Verify that image links in Markdown are valid and accessible.', category: 'formatter', slug: '/image-link-checker/', icon: 'search' },
  { id: 'footnote-validator', name: 'Footnote Validator', description: 'Validate footnote definitions and references in Markdown.', category: 'formatter', slug: '/footnote-validator/', icon: 'search' },
  { id: 'anchor-link-checker', name: 'Anchor Link Checker', description: 'Check anchor links in Markdown for correct targets.', category: 'formatter', slug: '/anchor-link-checker/', icon: 'search' },
  { id: 'markdown-diff-checker', name: 'Markdown Diff Checker', description: 'Compare two Markdown documents and highlight differences.', category: 'formatter', slug: '/markdown-diff-checker/', icon: 'search' },
  { id: 'markdown-compare-tool', name: 'Markdown Compare Tool', description: 'Side-by-side comparison of two Markdown documents.', category: 'formatter', slug: '/markdown-compare-tool/', icon: 'search' },
  { id: 'front-matter-validator', name: 'Front Matter Validator', description: 'Validate YAML front matter in Markdown files.', category: 'formatter', slug: '/front-matter-validator/', icon: 'search' },
  { id: 'yaml-front-matter-generator', name: 'YAML Front Matter Generator', description: 'Generate YAML front matter for Markdown files.', category: 'formatter', slug: '/yaml-front-matter-generator/', icon: 'code' },
  { id: 'toc-generator', name: 'TOC Generator', description: 'Generate a table of contents from Markdown headings.', category: 'formatter', slug: '/toc-generator/', icon: 'list' },
  { id: 'automatic-numbering', name: 'Automatic Numbering', description: 'Add automatic numbering to headings in Markdown.', category: 'formatter', slug: '/automatic-numbering/', icon: 'list' },
  { id: 'heading-renumber', name: 'Heading Renumber', description: 'Renumber heading levels in Markdown documents.', category: 'formatter', slug: '/heading-renumber/', icon: 'list' },
  { id: 'duplicate-heading-finder', name: 'Duplicate Heading Finder', description: 'Find duplicate headings in Markdown documents.', category: 'formatter', slug: '/duplicate-heading-finder/', icon: 'search' },
  { id: 'unused-reference-finder', name: 'Unused Reference Finder', description: 'Find unused reference-style links in Markdown.', category: 'formatter', slug: '/unused-reference-finder/', icon: 'search' },
  { id: 'markdown-statistics', name: 'Markdown Statistics', description: 'View detailed statistics about your Markdown documents.', category: 'formatter', slug: '/markdown-statistics/', icon: 'search' },
  { id: 'reading-time-calculator', name: 'Reading Time Calculator', description: 'Calculate the estimated reading time for Markdown content.', category: 'formatter', slug: '/reading-time-calculator/', icon: 'search' },
  { id: 'word-counter', name: 'Word Counter', description: 'Count words, characters, and paragraphs in Markdown.', category: 'formatter', slug: '/word-counter/', icon: 'search' },
  { id: 'character-counter', name: 'Character Counter', description: 'Count characters including and excluding spaces in Markdown.', category: 'formatter', slug: '/character-counter/', icon: 'search' },
  { id: 'markdown-spell-checker', name: 'Markdown Spell Checker', description: 'Check spelling in Markdown documents, ignoring code blocks.', category: 'formatter', slug: '/markdown-spell-checker/', icon: 'search' },
  { id: 'emoji-validator', name: 'Emoji Validator', description: 'Validate emoji syntax in Markdown documents.', category: 'formatter', slug: '/emoji-validator/', icon: 'search' },
  { id: 'checklist-validator', name: 'Checklist Validator', description: 'Validate task list syntax in Markdown documents.', category: 'formatter', slug: '/checklist-validator/', icon: 'search' },
  { id: 'code-fence-validator', name: 'Code Fence Validator', description: 'Validate code fence syntax and language tags in Markdown.', category: 'formatter', slug: '/code-fence-validator/', icon: 'search' },
  { id: 'html-in-markdown-checker', name: 'HTML-in-Markdown Checker', description: 'Check for inline HTML in Markdown and validate it.', category: 'formatter', slug: '/html-in-markdown-checker/', icon: 'search' },
  { id: 'markdown-accessibility-checker', name: 'Markdown Accessibility Checker', description: 'Check Markdown for accessibility issues.', category: 'formatter', slug: '/markdown-accessibility-checker/', icon: 'search' },
  { id: 'markdown-security-checker', name: 'Markdown Security Checker', description: 'Check Markdown for security vulnerabilities.', category: 'formatter', slug: '/markdown-security-checker/', icon: 'search' },
  { id: 'markdown-metadata-viewer', name: 'Markdown Metadata Viewer', description: 'View and edit metadata embedded in Markdown documents.', category: 'formatter', slug: '/markdown-metadata-viewer/', icon: 'search' },
  { id: 'markdown-quality-analyzer', name: 'Markdown Quality Analyzer', description: 'Analyze the quality and consistency of Markdown documents.', category: 'formatter', slug: '/markdown-quality-analyzer/', icon: 'search' },
  { id: 'markdown-project-analyzer', name: 'Markdown Project Analyzer', description: 'Analyze all Markdown files in a project for quality metrics.', category: 'formatter', slug: '/markdown-project-analyzer/', icon: 'search' },

  // ── Documentation Tools ──
  { id: 'readme-generator', name: 'README Generator', description: 'Generate professional README files for your projects.', category: 'documentation', slug: '/readme-generator/', icon: 'file' },
  { id: 'github-profile-readme-generator', name: 'GitHub Profile README Generator', description: 'Create a standout GitHub profile README.', category: 'documentation', slug: '/github-profile-readme-generator/', icon: 'file' },
  { id: 'changelog-generator', name: 'CHANGELOG Generator', description: 'Generate changelog files from git commits.', category: 'documentation', slug: '/changelog-generator/', icon: 'file' },
  { id: 'contributing-md-generator', name: 'CONTRIBUTING.md Generator', description: 'Generate contributing guidelines for open source projects.', category: 'documentation', slug: '/contributing-md-generator/', icon: 'file' },
  { id: 'license-generator', name: 'LICENSE Generator', description: 'Generate open source license files in Markdown.', category: 'documentation', slug: '/license-generator/', icon: 'file' },
  { id: 'code-of-conduct-generator', name: 'CODE_OF_CONDUCT Generator', description: 'Generate a code of conduct for your community.', category: 'documentation', slug: '/code-of-conduct-generator/', icon: 'file' },
  { id: 'security-md-generator', name: 'SECURITY.md Generator', description: 'Generate security policy documentation.', category: 'documentation', slug: '/security-md-generator/', icon: 'file' },
  { id: 'support-md-generator', name: 'SUPPORT.md Generator', description: 'Generate support documentation for your project.', category: 'documentation', slug: '/support-md-generator/', icon: 'file' },
  { id: 'issue-template-generator', name: 'ISSUE_TEMPLATE Generator', description: 'Create issue templates for GitHub repositories.', category: 'documentation', slug: '/issue-template-generator/', icon: 'file' },
  { id: 'pull-request-template-generator', name: 'PULL_REQUEST_TEMPLATE Generator', description: 'Create pull request templates for GitHub.', category: 'documentation', slug: '/pull-request-template-generator/', icon: 'file' },
  { id: 'release-notes-generator', name: 'Release Notes Generator', description: 'Generate release notes from git history.', category: 'documentation', slug: '/release-notes-generator/', icon: 'file' },
  { id: 'documentation-template-generator', name: 'Documentation Template Generator', description: 'Generate documentation templates for various project types.', category: 'documentation', slug: '/documentation-template-generator/', icon: 'file' },
  { id: 'api-documentation-generator', name: 'API Documentation Generator', description: 'Generate API documentation in Markdown format.', category: 'documentation', slug: '/api-documentation-generator/', icon: 'code' },
  { id: 'cli-documentation-generator', name: 'CLI Documentation Generator', description: 'Generate CLI tool documentation in Markdown.', category: 'documentation', slug: '/cli-documentation-generator/', icon: 'code' },
  { id: 'sdk-documentation-generator', name: 'SDK Documentation Generator', description: 'Generate SDK documentation in Markdown format.', category: 'documentation', slug: '/sdk-documentation-generator/', icon: 'code' },
  { id: 'component-documentation-generator', name: 'Component Documentation Generator', description: 'Generate UI component documentation in Markdown.', category: 'documentation', slug: '/component-documentation-generator/', icon: 'code' },
  { id: 'project-documentation-generator', name: 'Project Documentation Generator', description: 'Generate comprehensive project documentation.', category: 'documentation', slug: '/project-documentation-generator/', icon: 'file' },
  { id: 'wiki-generator', name: 'Wiki Generator', description: 'Generate wiki documentation from Markdown files.', category: 'documentation', slug: '/wiki-generator/', icon: 'file' },
  { id: 'faq-generator', name: 'FAQ Generator', description: 'Generate FAQ documents in Markdown format.', category: 'documentation', slug: '/faq-generator/', icon: 'file' },
  { id: 'installation-guide-generator', name: 'Installation Guide Generator', description: 'Generate installation guides in Markdown.', category: 'documentation', slug: '/installation-guide-generator/', icon: 'file' },
  { id: 'user-guide-generator', name: 'User Guide Generator', description: 'Generate user guides and manuals in Markdown.', category: 'documentation', slug: '/user-guide-generator/', icon: 'file' },
  { id: 'developer-guide-generator', name: 'Developer Guide Generator', description: 'Generate developer guides in Markdown format.', category: 'documentation', slug: '/developer-guide-generator/', icon: 'code' },
  { id: 'architecture-document-generator', name: 'Architecture Document Generator', description: 'Generate architecture documentation in Markdown.', category: 'documentation', slug: '/architecture-document-generator/', icon: 'layout' },
  { id: 'adr-generator', name: 'ADR Generator', description: 'Generate Architecture Decision Records in Markdown.', category: 'documentation', slug: '/adr-generator/', icon: 'file' },
  { id: 'roadmap-generator', name: 'Roadmap Generator', description: 'Generate product roadmaps in Markdown format.', category: 'documentation', slug: '/roadmap-generator/', icon: 'file' },
  { id: 'product-requirements-generator', name: 'Product Requirements Generator', description: 'Generate PRD documents in Markdown.', category: 'documentation', slug: '/product-requirements-generator/', icon: 'file' },
  { id: 'meeting-notes-generator', name: 'Meeting Notes Generator', description: 'Generate meeting notes templates in Markdown.', category: 'documentation', slug: '/meeting-notes-generator/', icon: 'file' },
  { id: 'sprint-notes-generator', name: 'Sprint Notes Generator', description: 'Generate sprint notes in Markdown format.', category: 'documentation', slug: '/sprint-notes-generator/', icon: 'file' },
  { id: 'release-checklist-generator', name: 'Release Checklist Generator', description: 'Generate release checklists in Markdown.', category: 'documentation', slug: '/release-checklist-generator/', icon: 'file' },
  { id: 'deployment-guide-generator', name: 'Deployment Guide Generator', description: 'Generate deployment guides in Markdown.', category: 'documentation', slug: '/deployment-guide-generator/', icon: 'file' },
  { id: 'troubleshooting-guide-generator', name: 'Troubleshooting Guide Generator', description: 'Generate troubleshooting guides in Markdown.', category: 'documentation', slug: '/troubleshooting-guide-generator/', icon: 'file' },
  { id: 'documentation-sidebar-generator', name: 'Documentation Sidebar Generator', description: 'Generate documentation sidebar navigation.', category: 'documentation', slug: '/documentation-sidebar-generator/', icon: 'list' },
  { id: 'mkdocs-navigation-generator', name: 'MkDocs Navigation Generator', description: 'Generate MkDocs navigation configuration.', category: 'documentation', slug: '/mkdocs-navigation-generator/', icon: 'list' },
  { id: 'docusaurus-sidebar-generator', name: 'Docusaurus Sidebar Generator', description: 'Generate Docusaurus sidebar configuration.', category: 'documentation', slug: '/docusaurus-sidebar-generator/', icon: 'list' },
  { id: 'hugo-front-matter-generator', name: 'Hugo Front Matter Generator', description: 'Generate Hugo front matter for Markdown content.', category: 'documentation', slug: '/hugo-front-matter-generator/', icon: 'code' },
  { id: 'jekyll-front-matter-generator', name: 'Jekyll Front Matter Generator', description: 'Generate Jekyll front matter for Markdown posts.', category: 'documentation', slug: '/jekyll-front-matter-generator/', icon: 'code' },
  { id: 'obsidian-vault-generator', name: 'Obsidian Vault Generator', description: 'Generate Obsidian vault structure from Markdown files.', category: 'documentation', slug: '/obsidian-vault-generator/', icon: 'file' },
  { id: 'knowledge-base-generator', name: 'Knowledge Base Generator', description: 'Generate knowledge base documentation in Markdown.', category: 'documentation', slug: '/knowledge-base-generator/', icon: 'file' },
  { id: 'docs-search-index-generator', name: 'Docs Search Index Generator', description: 'Generate search indexes for documentation sites.', category: 'documentation', slug: '/docs-search-index-generator/', icon: 'search' },
  { id: 'documentation-playground', name: 'Documentation Playground', description: 'Experiment with documentation formats in an interactive playground.', category: 'documentation', slug: '/documentation-playground/', icon: 'play' },

  // ── Generators ──
  { id: 'heading-generator', name: 'Heading Generator', description: 'Generate properly formatted Markdown headings at any level.', category: 'generator', slug: '/heading-generator/', icon: 'list' },
  { id: 'checklist-generator', name: 'Checklist Generator', description: 'Create interactive Markdown checklists and task lists.', category: 'generator', slug: '/checklist-generator/', icon: 'list' },
  { id: 'task-list-generator', name: 'Task List Generator', description: 'Generate task lists with checkboxes for Markdown.', category: 'generator', slug: '/task-list-generator/', icon: 'list' },
  { id: 'quote-generator', name: 'Quote Generator', description: 'Generate formatted blockquotes in Markdown.', category: 'generator', slug: '/quote-generator/', icon: 'edit' },
  { id: 'blockquote-generator', name: 'Blockquote Generator', description: 'Create styled blockquotes with attribution in Markdown.', category: 'generator', slug: '/blockquote-generator/', icon: 'edit' },
  { id: 'code-block-generator', name: 'Code Block Generator', description: 'Generate syntax-highlighted code blocks in Markdown.', category: 'generator', slug: '/code-block-generator/', icon: 'code' },
  { id: 'syntax-highlight-generator', name: 'Syntax Highlight Generator', description: 'Generate code blocks with language-specific syntax highlighting.', category: 'generator', slug: '/syntax-highlight-generator/', icon: 'code' },
  { id: 'image-markdown-generator', name: 'Image Markdown Generator', description: 'Generate Markdown image syntax with alt text and titles.', category: 'generator', slug: '/image-markdown-generator/', icon: 'image' },
  { id: 'link-generator', name: 'Link Generator', description: 'Generate Markdown links with text and titles.', category: 'generator', slug: '/link-generator/', icon: 'link' },
  { id: 'badge-generator', name: 'Badge Generator', description: 'Generate Markdown badges for your README files.', category: 'generator', slug: '/badge-generator/', icon: 'edit' },
  { id: 'shields-io-badge-builder', name: 'Shields.io Badge Builder', description: 'Build custom Shields.io badges in Markdown format.', category: 'generator', slug: '/shields-io-badge-builder/', icon: 'edit' },
  { id: 'emoji-picker', name: 'Emoji Picker', description: 'Browse and insert emojis into your Markdown documents.', category: 'generator', slug: '/emoji-picker/', icon: 'edit' },
  { id: 'keyboard-shortcut-generator', name: 'Keyboard Shortcut Generator', description: 'Generate keyboard shortcut Markdown syntax.', category: 'generator', slug: '/keyboard-shortcut-generator/', icon: 'edit' },
  { id: 'mermaid-diagram-generator', name: 'Mermaid Diagram Generator', description: 'Generate Mermaid diagram Markdown code interactively.', category: 'generator', slug: '/mermaid-diagram-generator/', icon: 'edit' },
  { id: 'flowchart-generator', name: 'Flowchart Generator', description: 'Generate flowchart diagrams in Mermaid Markdown.', category: 'generator', slug: '/flowchart-generator/', icon: 'edit' },
  { id: 'sequence-diagram-generator', name: 'Sequence Diagram Generator', description: 'Generate sequence diagrams in Mermaid Markdown.', category: 'generator', slug: '/sequence-diagram-generator/', icon: 'edit' },
  { id: 'gantt-chart-generator', name: 'Gantt Chart Generator', description: 'Generate Gantt charts in Mermaid Markdown.', category: 'generator', slug: '/gantt-chart-generator/', icon: 'edit' },
  { id: 'mind-map-generator', name: 'Mind Map Generator', description: 'Generate mind maps in Mermaid Markdown.', category: 'generator', slug: '/mind-map-generator/', icon: 'edit' },
  { id: 'pie-chart-generator', name: 'Pie Chart Generator', description: 'Generate pie charts in Mermaid Markdown.', category: 'generator', slug: '/pie-chart-generator/', icon: 'edit' },
  { id: 'timeline-generator', name: 'Timeline Generator', description: 'Generate timeline diagrams in Markdown.', category: 'generator', slug: '/timeline-generator/', icon: 'edit' },
  { id: 'callout-generator', name: 'Callout Generator', description: 'Generate callout boxes and alerts in Markdown.', category: 'generator', slug: '/callout-generator/', icon: 'edit' },
  { id: 'admonition-generator', name: 'Admonition Generator', description: 'Generate admonition blocks for documentation in Markdown.', category: 'generator', slug: '/admonition-generator/', icon: 'edit' },
  { id: 'footnote-generator', name: 'Footnote Generator', description: 'Generate footnotes for Markdown documents.', category: 'generator', slug: '/footnote-generator/', icon: 'edit' },
  { id: 'definition-list-generator', name: 'Definition List Generator', description: 'Generate definition lists in Markdown format.', category: 'generator', slug: '/definition-list-generator/', icon: 'list' },
  { id: 'math-formula-generator', name: 'Math Formula Generator', description: 'Generate LaTeX math formulas for Markdown.', category: 'generator', slug: '/math-formula-generator/', icon: 'code' },
  { id: 'latex-equation-generator', name: 'LaTeX Equation Generator', description: 'Generate LaTeX equations for Markdown documents.', category: 'generator', slug: '/latex-equation-generator/', icon: 'code' },
  { id: 'table-of-contents-generator', name: 'Table of Contents Generator', description: 'Generate a table of contents from Markdown headings.', category: 'generator', slug: '/table-of-contents-generator/', icon: 'list' },
  { id: 'collapsible-section-generator', name: 'Collapsible Section Generator', description: 'Generate collapsible details sections in Markdown.', category: 'generator', slug: '/collapsible-section-generator/', icon: 'edit' },
  { id: 'html-embed-generator', name: 'HTML Embed Generator', description: 'Generate HTML embeds for Markdown documents.', category: 'generator', slug: '/html-embed-generator/', icon: 'code' },
  { id: 'video-embed-generator', name: 'Video Embed Generator', description: 'Generate video embed code for Markdown documents.', category: 'generator', slug: '/video-embed-generator/', icon: 'image' },
  { id: 'audio-embed-generator', name: 'Audio Embed Generator', description: 'Generate audio embed Markdown for podcasts and music.', category: 'generator', slug: '/audio-embed-generator/', icon: 'image' },
  { id: 'youtube-embed-markdown', name: 'YouTube Embed Markdown', description: 'Generate YouTube video embed Markdown syntax.', category: 'generator', slug: '/youtube-embed-markdown/', icon: 'image' },
  { id: 'github-alert-generator', name: 'GitHub Alert Generator', description: 'Generate GitHub-style alerts in Markdown.', category: 'generator', slug: '/github-alert-generator/', icon: 'edit' },
  { id: 'wiki-link-generator', name: 'Wiki Link Generator', description: 'Generate wiki-style links for Markdown.', category: 'generator', slug: '/wiki-link-generator/', icon: 'link' },
  { id: 'tag-generator', name: 'Tag Generator', description: 'Generate tag metadata for Markdown documents.', category: 'generator', slug: '/tag-generator/', icon: 'edit' },
  { id: 'metadata-generator', name: 'Metadata Generator', description: 'Generate metadata sections for Markdown documents.', category: 'generator', slug: '/metadata-generator/', icon: 'edit' },
  { id: 'front-matter-generator', name: 'Front Matter Generator', description: 'Generate YAML front matter for Markdown files.', category: 'generator', slug: '/front-matter-generator/', icon: 'code' },
  { id: 'citation-generator', name: 'Citation Generator', description: 'Generate citations and references in Markdown.', category: 'generator', slug: '/citation-generator/', icon: 'edit' },
  { id: 'reference-list-generator', name: 'Reference List Generator', description: 'Generate reference-style link lists for Markdown.', category: 'generator', slug: '/reference-list-generator/', icon: 'list' },
  { id: 'markdown-snippet-generator', name: 'Markdown Snippet Generator', description: 'Generate reusable Markdown snippets and templates.', category: 'generator', slug: '/markdown-snippet-generator/', icon: 'edit' },

  // ── Diagram Tools ──
  { id: 'mermaid-live-editor', name: 'Mermaid Live Editor', description: 'Edit and preview Mermaid diagrams in real time.', category: 'diagram', slug: '/mermaid-live-editor/', icon: 'edit' },
  { id: 'mermaid-flowchart-generator', name: 'Mermaid Flowchart Generator', description: 'Generate flowcharts using Mermaid diagram syntax.', category: 'diagram', slug: '/mermaid-flowchart-generator/', icon: 'edit' },
  { id: 'mermaid-sequence-diagram-generator', name: 'Mermaid Sequence Diagram Generator', description: 'Generate sequence diagrams using Mermaid syntax.', category: 'diagram', slug: '/mermaid-sequence-diagram-generator/', icon: 'edit' },
  { id: 'mermaid-er-diagram-generator', name: 'Mermaid ER Diagram Generator', description: 'Generate entity-relationship diagrams using Mermaid.', category: 'diagram', slug: '/mermaid-er-diagram-generator/', icon: 'edit' },
  { id: 'mermaid-gantt-generator', name: 'Mermaid Gantt Generator', description: 'Generate Gantt charts using Mermaid diagram syntax.', category: 'diagram', slug: '/mermaid-gantt-generator/', icon: 'edit' },
  { id: 'mermaid-mind-map-generator', name: 'Mermaid Mind Map Generator', description: 'Generate mind maps using Mermaid diagram syntax.', category: 'diagram', slug: '/mermaid-mind-map-generator/', icon: 'edit' },
  { id: 'mermaid-pie-chart-generator', name: 'Mermaid Pie Chart Generator', description: 'Generate pie charts using Mermaid diagram syntax.', category: 'diagram', slug: '/mermaid-pie-chart-generator/', icon: 'edit' },
  { id: 'mermaid-timeline-generator', name: 'Mermaid Timeline Generator', description: 'Generate timelines using Mermaid diagram syntax.', category: 'diagram', slug: '/mermaid-timeline-generator/', icon: 'edit' },
  { id: 'plantuml-to-markdown', name: 'PlantUML to Markdown', description: 'Convert PlantUML diagrams to Markdown Mermaid format.', category: 'diagram', slug: '/plantuml-to-markdown/', icon: 'code' },
  { id: 'markdown-diagram-preview', name: 'Markdown Diagram Preview', description: 'Preview diagrams embedded in Markdown documents.', category: 'diagram', slug: '/markdown-diagram-preview/', icon: 'eye' },
  { id: 'graphviz-to-markdown', name: 'Graphviz to Markdown', description: 'Convert Graphviz DOT diagrams to Markdown.', category: 'diagram', slug: '/graphviz-to-markdown/', icon: 'code' },
  { id: 'svg-to-markdown-embed', name: 'SVG to Markdown Embed', description: 'Generate Markdown embed code for SVG diagrams.', category: 'diagram', slug: '/svg-to-markdown-embed/', icon: 'image' },
  { id: 'image-map-generator', name: 'Image Map Generator', description: 'Create clickable image maps in Markdown.', category: 'diagram', slug: '/image-map-generator/', icon: 'image' },
  { id: 'diagram-validator', name: 'Diagram Validator', description: 'Validate Mermaid diagram syntax and structure.', category: 'diagram', slug: '/diagram-validator/', icon: 'search' },
  { id: 'mermaid-theme-builder', name: 'Mermaid Theme Builder', description: 'Build custom themes for Mermaid diagrams.', category: 'diagram', slug: '/mermaid-theme-builder/', icon: 'edit' },
  { id: 'mermaid-exporter', name: 'Mermaid Exporter', description: 'Export Mermaid diagrams to SVG, PNG, or image formats.', category: 'diagram', slug: '/mermaid-exporter/', icon: 'code' },
  { id: 'mermaid-optimizer', name: 'Mermaid Optimizer', description: 'Optimize Mermaid diagram code for better rendering.', category: 'diagram', slug: '/mermaid-optimizer/', icon: 'code' },
  { id: 'mermaid-formatter', name: 'Mermaid Formatter', description: 'Format Mermaid diagram code with proper indentation.', category: 'diagram', slug: '/mermaid-formatter/', icon: 'code' },
  { id: 'mermaid-snippet-library', name: 'Mermaid Snippet Library', description: 'Browse and use pre-built Mermaid diagram snippets.', category: 'diagram', slug: '/mermaid-snippet-library/', icon: 'edit' },
  { id: 'diagram-playground', name: 'Diagram Playground', description: 'Experiment with diagram syntax in an interactive playground.', category: 'diagram', slug: '/diagram-playground/', icon: 'play' },

  // ── Utilities ──
  { id: 'markdown-preview', name: 'Markdown Preview', description: 'Preview rendered Markdown in real time.', category: 'utility', slug: '/markdown-preview/', icon: 'eye' },
  { id: 'markdown-viewer', name: 'Markdown Viewer', description: 'View and browse Markdown documents with a clean reader interface.', category: 'utility', slug: '/markdown-viewer/', icon: 'eye' },
  { id: 'markdown-search', name: 'Markdown Search', description: 'Search through Markdown documents for specific content.', category: 'utility', slug: '/markdown-search/', icon: 'search' },
  { id: 'markdown-file-merger', name: 'Markdown File Merger', description: 'Merge multiple Markdown files into a single document.', category: 'utility', slug: '/markdown-file-merger/', icon: 'file' },
  { id: 'markdown-file-splitter', name: 'Markdown File Splitter', description: 'Split large Markdown documents into smaller files.', category: 'utility', slug: '/markdown-file-splitter/', icon: 'file' },
  { id: 'markdown-batch-processor', name: 'Markdown Batch Processor', description: 'Process multiple Markdown files with batch operations.', category: 'utility', slug: '/markdown-batch-processor/', icon: 'file' },
  { id: 'markdown-zip-generator', name: 'Markdown ZIP Generator', description: 'Package Markdown files into ZIP archives.', category: 'utility', slug: '/markdown-zip-generator/', icon: 'file' },
  { id: 'markdown-metadata-extractor', name: 'Markdown Metadata Extractor', description: 'Extract metadata from Markdown documents.', category: 'utility', slug: '/markdown-metadata-extractor/', icon: 'search' },
  { id: 'markdown-link-extractor', name: 'Markdown Link Extractor', description: 'Extract all links from Markdown documents.', category: 'utility', slug: '/markdown-link-extractor/', icon: 'link' },
  { id: 'markdown-image-extractor', name: 'Markdown Image Extractor', description: 'Extract all image references from Markdown documents.', category: 'utility', slug: '/markdown-image-extractor/', icon: 'image' },
  { id: 'markdown-attachment-manager', name: 'Markdown Attachment Manager', description: 'Manage file attachments linked in Markdown documents.', category: 'utility', slug: '/markdown-attachment-manager/', icon: 'file' },
  { id: 'markdown-folder-generator', name: 'Markdown Folder Generator', description: 'Generate folder structure documentation in Markdown.', category: 'utility', slug: '/markdown-folder-generator/', icon: 'file' },
  { id: 'markdown-sitemap-generator', name: 'Markdown Sitemap Generator', description: 'Generate sitemaps from Markdown documentation.', category: 'utility', slug: '/markdown-sitemap-generator/', icon: 'file' },
  { id: 'markdown-rss-generator', name: 'Markdown RSS Generator', description: 'Generate RSS feeds from Markdown content.', category: 'utility', slug: '/markdown-rss-generator/', icon: 'file' },
  { id: 'markdown-feed-generator', name: 'Markdown Feed Generator', description: 'Generate feed files from Markdown documents.', category: 'utility', slug: '/markdown-feed-generator/', icon: 'file' },
  { id: 'markdown-archive-generator', name: 'Markdown Archive Generator', description: 'Generate archive pages from Markdown files.', category: 'utility', slug: '/markdown-archive-generator/', icon: 'file' },
  { id: 'markdown-import-tool', name: 'Markdown Import Tool', description: 'Import content from external sources into Markdown format.', category: 'utility', slug: '/markdown-import-tool/', icon: 'file' },
  { id: 'markdown-export-tool', name: 'Markdown Export Tool', description: 'Export Markdown documents to various output formats.', category: 'utility', slug: '/markdown-export-tool/', icon: 'file' },
  { id: 'markdown-version-comparator', name: 'Markdown Version Comparator', description: 'Compare different versions of Markdown documents.', category: 'utility', slug: '/markdown-version-comparator/', icon: 'search' },
  { id: 'markdown-history-viewer', name: 'Markdown History Viewer', description: 'View the edit history of Markdown documents.', category: 'utility', slug: '/markdown-history-viewer/', icon: 'eye' },
  { id: 'markdown-snippet-manager', name: 'Markdown Snippet Manager', description: 'Manage and organize reusable Markdown snippets.', category: 'utility', slug: '/markdown-snippet-manager/', icon: 'file' },
  { id: 'markdown-clipboard-tool', name: 'Markdown Clipboard Tool', description: 'Copy and paste Markdown content with smart formatting.', category: 'utility', slug: '/markdown-clipboard-tool/', icon: 'edit' },
  { id: 'markdown-template-manager', name: 'Markdown Template Manager', description: 'Create and manage Markdown templates for reuse.', category: 'utility', slug: '/markdown-template-manager/', icon: 'file' },
  { id: 'markdown-theme-generator', name: 'Markdown Theme Generator', description: 'Generate custom CSS themes for Markdown rendering.', category: 'utility', slug: '/markdown-theme-generator/', icon: 'edit' },
  { id: 'markdown-css-generator', name: 'Markdown CSS Generator', description: 'Generate CSS styles for Markdown rendered content.', category: 'utility', slug: '/markdown-css-generator/', icon: 'code' },
  { id: 'markdown-html-exporter', name: 'Markdown HTML Exporter', description: 'Export Markdown documents to standalone HTML files.', category: 'utility', slug: '/markdown-html-exporter/', icon: 'code' },
  { id: 'markdown-pdf-exporter', name: 'Markdown PDF Exporter', description: 'Export Markdown documents to PDF format.', category: 'utility', slug: '/markdown-pdf-exporter/', icon: 'file' },
  { id: 'markdown-epub-exporter', name: 'Markdown EPUB Exporter', description: 'Export Markdown documents to EPUB ebook format.', category: 'utility', slug: '/markdown-epub-exporter/', icon: 'file' },
  { id: 'markdown-print-formatter', name: 'Markdown Print Formatter', description: 'Format Markdown documents for printing.', category: 'utility', slug: '/markdown-print-formatter/', icon: 'file' },
  { id: 'markdown-seo-analyzer', name: 'Markdown SEO Analyzer', description: 'Analyze Markdown content for SEO optimization.', category: 'utility', slug: '/markdown-seo-analyzer/', icon: 'search' },
  { id: 'markdown-accessibility-report', name: 'Markdown Accessibility Report', description: 'Generate accessibility reports for Markdown documents.', category: 'utility', slug: '/markdown-accessibility-report/', icon: 'search' },
  { id: 'markdown-link-shortener', name: 'Markdown Link Shortener', description: 'Shorten URLs embedded in Markdown documents.', category: 'utility', slug: '/markdown-link-shortener/', icon: 'link' },
  { id: 'markdown-image-optimizer', name: 'Markdown Image Optimizer', description: 'Optimize images referenced in Markdown documents.', category: 'utility', slug: '/markdown-image-optimizer/', icon: 'image' },
  { id: 'markdown-asset-manager', name: 'Markdown Asset Manager', description: 'Manage assets like images and files for Markdown projects.', category: 'utility', slug: '/markdown-asset-manager/', icon: 'file' },
  { id: 'markdown-project-explorer', name: 'Markdown Project Explorer', description: 'Explore and navigate Markdown project structures.', category: 'utility', slug: '/markdown-project-explorer/', icon: 'search' },
  { id: 'markdown-package-builder', name: 'Markdown Package Builder', description: 'Build distributable packages from Markdown projects.', category: 'utility', slug: '/markdown-package-builder/', icon: 'file' },
  { id: 'markdown-workspace', name: 'Markdown Workspace', description: 'A full workspace for managing multiple Markdown projects.', category: 'utility', slug: '/markdown-workspace/', icon: 'layout' },
  { id: 'markdown-backup-tool', name: 'Markdown Backup Tool', description: 'Back up your Markdown files and projects.', category: 'utility', slug: '/markdown-backup-tool/', icon: 'file' },
  { id: 'markdown-restore-tool', name: 'Markdown Restore Tool', description: 'Restore Markdown files from backups.', category: 'utility', slug: '/markdown-restore-tool/', icon: 'file' },
  { id: 'markdown-sync-tool', name: 'Markdown Sync Tool', description: 'Sync Markdown files across directories and devices.', category: 'utility', slug: '/markdown-sync-tool/', icon: 'file' },
  { id: 'markdown-api-builder', name: 'Markdown API Builder', description: 'Build APIs that serve Markdown content.', category: 'utility', slug: '/markdown-api-builder/', icon: 'code' },
  { id: 'markdown-cms-exporter', name: 'Markdown CMS Exporter', description: 'Export CMS content into Markdown format.', category: 'utility', slug: '/markdown-cms-exporter/', icon: 'file' },
  { id: 'markdown-blog-generator', name: 'Markdown Blog Generator', description: 'Generate a blog from Markdown content files.', category: 'utility', slug: '/markdown-blog-generator/', icon: 'file' },
  { id: 'markdown-newsletter-generator', name: 'Markdown Newsletter Generator', description: 'Generate newsletters from Markdown content.', category: 'utility', slug: '/markdown-newsletter-generator/', icon: 'file' },
  { id: 'markdown-resume-builder', name: 'Markdown Resume Builder', description: 'Build a professional resume using Markdown.', category: 'utility', slug: '/markdown-resume-builder/', icon: 'file' },
  { id: 'markdown-portfolio-generator', name: 'Markdown Portfolio Generator', description: 'Generate a portfolio website from Markdown content.', category: 'utility', slug: '/markdown-portfolio-generator/', icon: 'file' },
  { id: 'markdown-static-site-builder', name: 'Markdown Static Site Builder', description: 'Build static sites from Markdown source files.', category: 'utility', slug: '/markdown-static-site-builder/', icon: 'code' },
  { id: 'markdown-component-library', name: 'Markdown Component Library', description: 'Build a component library documented in Markdown.', category: 'utility', slug: '/markdown-component-library/', icon: 'code' },
  { id: 'markdown-asset-bundler', name: 'Markdown Asset Bundler', description: 'Bundle assets for Markdown-based projects.', category: 'utility', slug: '/markdown-asset-bundler/', icon: 'file' },
  { id: 'markdown-toolkit', name: 'Markdown Toolkit', description: 'A comprehensive toolkit for all Markdown-related tasks.', category: 'utility', slug: '/markdown-toolkit/', icon: 'wand' },
]
